# [信息]
site_name: 学习笔记 # 左上角标题
site_url: https://YMnRb.github.io/StudyNotes

# [导航结构]
nav:
  - 主页:
    - 导引: index.md

# [主题]
theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep purple
      accent: purple
      toggle:
        icon: octicons/sun-16 
        name: 切换至黑暗主题
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      accent: purple
      toggle:
        icon: octicons/moon-16
        name: 切换至明亮主题
  # font: false
  language: zh  # https://squidfunk.github.io/mkdocs-material/setup/changing-the-language/#site-language
  icon:
    logo: material/book
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    # - navigation.path # Insiders only
    - navigation.indexes

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem

extra_javascript:
  # 在项目中使用 MathJax
  # https://squidfunk.github.io/mkdocs-material/reference/math/?h=math+jax#mathjax
  - .config/javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - .config/stylesheets/fonts.css
  - .config/stylesheets/extra.css