# [Info]
site_name: 学习笔记 # 左上角标题
site_url: https://YMnRb.github.io/StudyNotes

# [Navigtion]
nav:
  - 主页:
    - 导引: index.md
  - 科学:
    - 导引: science/index.md
    - 电学: 
      - 导引: science/electricity/index.md
      - 电现象: science/electricity/1.md
      - 电流、电压和电阻: science/electricity/3.md

theme:
  name: material
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep purple
      accent: purple
      toggle:
        icon: octicons/sun-16 
        name: 切换至夜间模式
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      accent: purple
      toggle:
        icon: octicons/moon-16
        name: 切换至日间模式
  # set the site language
  # https://squidfunk.github.io/mkdocs-material/setup/changing-the-language/#site-language
  language: zh 
  icon:
    logo: material/book
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.path
    - navigation.prune
    - navigation.indexes
  # set the font
  # https://squidfunk.github.io/mkdocs-material/setup/changing-the-fonts/#configuration
  font:
    text: 思源黑体
    code: Fira Mono

# to use KaTeX within the project
# https://squidfunk.github.io/mkdocs-material/reference/math/#katex
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
extra_javascript:
  - javascripts/katex.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/contrib/auto-render.min.js
extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.css